name: Render Bookdown as .pdf, publish if merging to `master`

on:
  push:
      branches:
        - master
  pull_request:
    branches:
      - master

jobs:
  build_bookdown:
    runs-on: ubuntu-latest    
    container: rocker/verse
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: Build
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book', output_dir = 'public')"
      - name: Deploy
        if: success() && github.event_name == 'push' #only publish pdf on merge with master
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pdf
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}